name: Package

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: npm install

      - run: CSC_IDENTITY_AUTO_DISCOVERY=false npm run build:mac

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          path: dist/pulls-*.dmg
