name: Package

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win, mac, linux]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: npm install

      - run: npm run build:${{ matrix.os }}

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
